services:
  db:
    image: postgres:15-alpine
    container_name: lex_uz_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 2005
      POSTGRES_DB: lex_uz_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: lex_uz_app
    ports:
      - "8000:8000"
    env_file:
      - .env      # 📌📌📌 Mana shu kerak edi
    environment:
      DATABASE_URL: postgresql://postgres:2005@db:5432/lex_uz_db
    volumes:
      - ./app:/app/app
      - ./main.py:/app/main.py
      - upload_temp:/tmp/uploads
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

volumes:
  postgres_data:
  upload_temp:
